  
name: Test and create report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: run test
      run: npm run test      
    - name: Copy History
      if: always()
      run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history # it copies old histoty to the current results to make report with history
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload Artifact   #we need to upload ./allure-results to make report with all jobs at the last job
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results-test
        path: ./allure-results        
    - name: Generate Report
      if: always()
      run: npm run allure:generate    #generates report for current job with history of past runs
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@3.1.0  #deploy current report (need it to take history from ./docs/history)
      if: always()
      with:
        ACCESS_TOKEN: ${{ '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' }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should deploy.
        TARGET_FOLDER: docs
  test2:
    if: always()  
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: run test
      run: npm run test      
    - name: Copy History
      if: always()
    # trying to save history of previous runs if it is exists
      run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history 
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results-test2
        path: ./allure-results        
    - name: Generate Report
      if: always()
      run: npm run allure:generate    
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@3.1.0
      if: always()
      with:
        ACCESS_TOKEN: ${{ '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' }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should deploy.
        TARGET_FOLDER: docs
  test1:
    if: always()  
    needs: [test, test2]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: run test1
      run: npm run test1
#     - name: Display structure of downloaded files
#       run: ls -R
    - name: Copy History
      if: always()
      run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results-test1
        path: ./allure-results
#     - uses: actions/checkout@v2
#     - run: npm i
    - name: Download artifacts  #download all artifacts from current workflow to current proj dir at the VM
      if: always()
      uses: actions/download-artifact@v2
    - name: Unpack artifacts #this copies results of all jobs but dont copy history (/*.*  only files with extension)
      if: always()
      run: sudo cp -r $(pwd)/allure-results-test/*.* $(pwd)/allure-results/ && sudo cp -r  $(pwd)/allure-results-test2/*.* $(pwd)/allure-results/ && sudo cp -r $(pwd)/allure-results-test1/*.* $(pwd)/allure-results/
    - name: Display structure of downloaded files
      run: ls -R
    - name: Generate Report   #this generates our final report with all jobs results and histories
      if: always()
      run: npm run allure:generate
    - name: Deploy report      
      uses: JamesIves/github-pages-deploy-action@3.1.0  #deploy final report so we could see all jobs results
      if: always()
      with:
        ACCESS_TOKEN: ${{ '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' }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should 
        TARGET_FOLDER: docs
    - name: Pushes docs to another repository           #if needs we may deploy report from closed repo to open repo with configured GH Pages (if you dont use GH Enterprise you cant use GH pages on closed repo)
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
      with:
        source-directory: 'docs'
        destination-github-username: 'ToActions'
        destination-repository-name: 'HtmlActions'
        user-email: s.fart2012@gmail.com
        target-branch: main
